import { useEffect, useState } from "react";
import API from "../../services/apiClient";

export default function SystemSettings() {
  const [capabilities, setCapabilities] = useState(null); const [message, setMessage] = useState("");
  const [preferences, setPreferences] = useState(() => JSON.parse(localStorage.getItem("safety-dashboard-preferences") || '{"autoRefresh":true,"notifyOnHighRisk":true}'));
  useEffect(() => { API.get("/alerts/capabilities").then((response) => setCapabilities(response.data.data)).catch(() => setMessage("Alert service status is unavailable.")); }, []);
  const save = () => { localStorage.setItem("safety-dashboard-preferences", JSON.stringify(preferences)); setMessage("Local dashboard preferences saved."); };
  return <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 p-5"><h3 className="font-semibold text-slate-800">Alert delivery</h3><p className="mt-1 text-sm text-slate-500">Current backend capability status.</p><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between rounded-lg bg-slate-50 p-3"><span>Email alerts</span><strong className={capabilities?.emailAlertsConfigured ? "text-emerald-700" : "text-amber-700"}>{capabilities ? (capabilities.emailAlertsConfigured ? "Configured" : "Not configured") : "Checking…"}</strong></div><div className="flex justify-between rounded-lg bg-slate-50 p-3"><span>Mobile push alerts</span><strong className="text-amber-700">{capabilities?.pushDeliveryIntegrated ? "Integrated" : "Registration only"}</strong></div><p className="text-xs text-slate-500">Push delivery requires Firebase Cloud Messaging credentials; device-token registration is already available.</p></div></section><section className="rounded-xl border border-slate-200 p-5"><h3 className="font-semibold text-slate-800">Operator preferences</h3><p className="mt-1 text-sm text-slate-500">Stored in this browser for the active operator.</p><div className="mt-5 space-y-3"><label className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>Enable automatic dashboard refresh</span><input type="checkbox" checked={preferences.autoRefresh} onChange={(e) => setPreferences({ ...preferences, autoRefresh: e.target.checked })} /></label><label className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>Highlight high-risk visitors</span><input type="checkbox" checked={preferences.notifyOnHighRisk} onChange={(e) => setPreferences({ ...preferences, notifyOnHighRisk: e.target.checked })} /></label><button onClick={save} className="w-full rounded-lg bg-sky-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-sky-700">Save preferences</button></div></section>{message && <p className="lg:col-span-2 rounded-lg bg-sky-50 p-3 text-sm text-sky-700">{message}</p>}</div>;
}
